[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = "j91kd33adokz"
  CONTENTFUL_ACCESS_TOKEN = "9e9BJ7-HPSOnqCewnqGx78aNN_i9ABbtcuo7VshXcCs"
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = "OrzIXJV2dzI4O2UH-us_G4fpbz0WOb8rmSHigZd3gNI"
